function [res, Jac] = fpe_residual(theta, theta_dot, m, h, vx, h_dot, J, g)

res= ((m*h*(vx*cos(theta)+h_dot*sin(theta))*cos(theta)+J*theta_dot*(cos(theta))^2)^2/...
     (m*h^2 + J*(cos(theta))^2))+2*m*g*h*cos(theta)*(cos(theta)-1);
 
Jac = ((J*theta_dot*cos(theta)^2+h*m*cos(theta)*(vx*cos(theta)+h_dot*sin(theta)))*(-h*m*cos(theta)*(h_dot*cos(theta)-vx*sin(theta))...
    +h*m*sin(theta)*(vx*cos(theta)+h_dot*sin(theta))+J*theta_dot*cos(theta)*sin(theta)*2.0)*-2.0)/(h^2*m+J*cos(theta)^2)...
    -g*h*m*cos(theta)*sin(theta)*2.0+J*cos(theta)*sin(theta)*(J*theta_dot*cos(theta)^2+...
    h*m*cos(theta)*(vx*cos(theta)+h_dot*sin(theta)))^2*1.0/(h^2*m+J*cos(theta)^2)^2*2.0...
    -g*h*m*sin(theta)*(cos(theta)-1.0)*2.0;
end